### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by nld9d** [peterrakolcza/homebridge-ngbs-icon-thermostat#3]
**Describe The Bug:**
Error: certificate has expired

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
[5/20/2024, 3:34:36 PM] [homebridge-ngbs-icon-thermostat] Error: certificate has expired
TypeError: Cannot read properties of undefined (reading 'includes')
    at getDevices (/volume1/homebridge/node_modules/homebridge-ngbs-icon-thermostat/src/client.ts:107:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NGBSiCONThermostat.discoverDevices (/volume1/homebridge/node_modules/homebridge-ngbs-icon-thermostat/src/platform.ts:75:25)
[5/20/2024, 3:34:36 PM] [homebridge-ngbs-icon-thermostat] Child bridge process ended
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.1.1
* **Homebridge Version**: 1.8.2
* **Node.js Version**: 20.9
* **NPM Version**: 
* **Operating System**: Synology

**Comment by nld9d** [comment]
Very nice work. Congratulations. Thank you for making this plugin.

**Comment by peterrakolcza** [comment]
Thank you for your feedback! 

Unfortunately the SSL certificate expired on the [NGBS](www.enzoldhazam.com) side. I could disable the verification, however that would decrease security. Please be patient until the NGBS solves this issue.

**Comment by nld9d** [comment]
Thank you for the quick reply. I appreciate it. 
In this case, let's wait while the NGBS solve the issue.
Best

**Comment by peterrakolcza** [comment]
It seems they have fixed the issue on their side. Could you please check now?

**Comment by gydavid** [comment]
Unfortunately the ssl cert is still bad.

**Comment by nld9d** [comment]
It works now
